### ISSUE TITLE
在我的Win10中主界面出现问题

### ISSUE THREAD

**Issue by piratf** [sshwsfc/django-xadmin#272]
![image](https://cloud.githubusercontent.com/assets/9389616/9349766/fce5a636-467c-11e5-980c-95a6fc525929.png)
Chrome44.0.2403 下
![image](https://cloud.githubusercontent.com/assets/9389616/9349836/b85ff222-467d-11e5-87fb-3d72f8cad474.png)
edge20.10240下
![image](https://cloud.githubusercontent.com/assets/9389616/9349838/c1cb208e-467d-11e5-83c5-08af16a03f7c.png)
IE11下

我打开demo的主页之后情况如图所示，Console没有报错，您方便检查一下吗？~谢谢

**Comment by alexsilva** [comment]
The demo site is buggy. Whatever operating system or browser, the problems will be the same.

**Comment by piratf** [comment]
Got it, Thank you. : )
